name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos_big_sur:
    runs-on: macos-11.0

    strategy:
      matrix:
        xcode:
          - "11.7" # Swift 5.2
          - "12.2" # Swift 5.3

    name: "macOS Big Sur (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-
      - name: Build and Test
        run: |
          swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  macos_catalina:
    runs-on: macos-10.15

    strategy:
      matrix:
        xcode:
          - "11.7" # Swift 5.2
          - "12" # Swift 5.3

    name: "macOS Catalina (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-
      - name: Build and Test
        run: |
          swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        swift:
          - "5.3"
          - "5.2"

    name: "Linux (Swift ${{ matrix.swift }})"

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-swift-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-swift-${{ matrix.swift }}-
      - name: Build and Test
        run: |
          swift test --enable-test-discovery
